api/urls.py
from django.urls import path
from . import views


app_name = 'api'
urlpatterns = [
    path('todo/list/', views.ApiTodoLV.as_view(), name='list'),
    path('todo/<int:pk>/delete/', views.ApiTodoDelV.as_view(), name='delete'),
    path('todo/create/', views.ApiTodoCV.as_view(), name='create'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.HomeView.as_view(), name='home'),
    path('todo/', include('todo.urls')),
    path('api/', include('api.urls')),
]

todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.TodoTV.as_view(), name='index'),
]

api/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models


class Todo(models.Model):
    name = models.CharField('NAME', max_length=5, blank=True)
    todo = models.CharField('TODO', max_length=50)

    def __str__(self):
        return self.todo

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.name: # name에 값이 없다면
            self.name = '홍길동' # name에 홍길동을 넣고 저장하라
        super().save()

api/views.py
import json

from django.forms import model_to_dict
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt, ensure_csrf_cookie
from django.views.generic.edit import BaseDeleteView, BaseCreateView
from django.views.generic.list import BaseListView

from todo.models import Todo


@method_decorator(ensure_csrf_cookie, name='dispatch')
class ApiTodoLV(BaseListView): # 테이블에서 데이터 가져오기
    model = Todo
    # template_name = ''
    # 요청이 get 방식으로 온다.
    # def get(self, request, *args, **kwargs):
    #     tmpList = [
    #         {'id': 1, 'name': '이창석', 'todo': '오늘 하루는 즐거운 노래로 시작해보자!!'},
    #         {'id': 2, 'name': '이순신', 'todo': '저에게 힘을 주소서!!'},
    #     ]
    #     return JsonResponse(data=tmpList, safe=False)

    def render_to_response(self, context, **response_kwargs): # 여기서 하는 일은 JsonResponse를 리턴하는 것이다.
        # get_queryset() 메서드에서 테이블로 부터 레코드를 가져와서
        todoList = list(context['object_list'].values()) # 테이블에서 가져온 레코드들을 Dict형태로 풀어준다.
        return JsonResponse(data=todoList, safe=False)


class ApiTodoDelV(BaseDeleteView): # axios.delete
    model = Todo

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object() # Todo 테이블에서 해당 레코드를 찾아서  self.object 변수에 대입
        self.object.delete() # 테이블에서 해당 레코드가 삭제된다.
        return JsonResponse(data={}, status=204) # dict 형태이기 때문에 safe=True 생략가능, status는 204로 변경


class ApiTodoCV(BaseCreateView):
    model = Todo
    fields = '__all__'
    # template name이나 sccess_url 은 JsonResponse 할 경우 필요가 없다.

    def get_form_kwargs(self): # request.body 로 받기 위해 오버라이딩 해준다.
        kwargs = super().get_form_kwargs()
        kwargs['data'] = json.loads(self.request.body) # [!] byte string을 dict 타입으로 변경해줘야 한다.
        return kwargs

    def form_valid(self, form):
        print("form_valid()", form)
        self.object = form.save() # 테이블에 새로 생성 된 레코드를 self.object 에 저장해준다.
        newTodo = model_to_dict(self.object) # self.object 타입이 모델 타입이기 때문에 dict 타입으로 변경해줘야 한다.
        print(f"newTodo: {newTodo}") # f 스트링
        return JsonResponse(data=newTodo, status=201)

    def form_invalid(self, form): # 에러내용을 http 로 전송하는
        print("form_invalid()", form)
        print("form_invalid()", self.request.POST) # print로 찍어보니 POST 에는 데이터가 들어있지 않은 걸 확인할 수 있다.
        print("form_invalid()", self.request.body.decode('utf8')) # body의 경우 byte string 타입이므로 Decode를 해준다.
        return JsonResponse(data=form.errors, status=400)

mysite/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

todo/views.py
from django.views.generic import TemplateView


class TodoTV(TemplateView):
    template_name = 'todo/todo_index.html'

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ko">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}home.html{% endblock %}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">

    {% block extra-style %}{% endblock %}

</head>

<body style="padding-top:90px;">

<!-- Main Menu -->
<nav class="navbar navbar-expand-sm navbar-dark bg-primary fixed-top">

    <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Vue-Django System</span>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'home' %}">Home</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'todo:index' %}">Todo</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'home' %}">Blog(todo)</a></li>

            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Util</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                    <div class="dropdown-divider"></div>
                </div>
            </li>
        </ul>

        <form class="form-inline my-2">
            <input class="form-control mr-sm-2" type="search" placeholder="Search">
        </form>

        <ul class="navbar-nav ml-5 mr-5">
            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                    <i class="fas fa-user"></i>&nbsp; Anonymous &nbsp;</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'home' %}">Login</a>
                    <a class="dropdown-item" href="{% url 'home' %}">Register</a>
                </div>
            </li>
        </ul>

    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

{% block footer %}{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

{% block extra-script %}{% endblock %}

</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<style type="text/css">

.home-window {
    background-image: url("{% static 'img/lion.jpg' %}");
    background-repeat: no-repeat;
    background-position: center;
    background-size: 100%;
    height: 500px;
    border-top: 10px solid #ccc;
    border-bottom: 10px solid #ccc;
    color: yellow;
    padding: 20px 0 0 20px;
}
.title {
    color: #c80;
    font-weight: bold;
}
.powered {
    position: relative;
    top: 77%;
    color: #cc0;
    font-style: italic;
}

.footer-wrapper {
    background: #456;
    color: #eee;
    line-height: 50px;
}
.footer-wrapper a {
    color: #ff9;    /* footer-right text */
}
.footer-wrapper a:hover {
    color: #0ff;
}
footer ul li {
    text-align: center;
}

</style>
{% endblock extra-style %}

{% block content %}
    <div class="home-window">
        <h2 class="title">Django - Python Web Programming</h2>
        <h4 class="powered"><i class="fas fa-cog"></i> powered by django and bootstrap.</h4>
    </div>

    <hr style="margin: 10px 0;">

    <div class="row text-center">
        <div class="col-sm-6">
            <h3>Todo App</h3>
            <p>With Todo app, you can manage, prioritize, and complete the most important things
                you need to do every day. I can focus on the most important things
                and I can do my day more deliberately.
                You can also share lists with colleagues, friends, and family.</p>
        </div>
        <div class="col-sm-6">
            <h3>Blog App</h3>
            <p>This application makes it possible to log daily events or write your own interests
                such as hobbies, techniques, etc.
                A typical blog combines text, digital images, and links to other blogs, web pages,
                and other media related to its topic.</p>
        </div>
    </div>
{% endblock content %}

{% block footer %}
<footer class="fixed-bottom footer-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <p>Copyright &copy; 2019 DjangoBook by shkim</p>
            </div>
            <div class="col-md-8">
                <ul class="list-inline float-right">
                    <li class="list-inline-item">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Introduction</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Help</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Policy</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Something</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>
{% endblock footer %}

{% block extra-script %}
<script>
$(function () {
    $('[data-toggle=tooltip]').tooltip();
});
</script>
{% endblock extra-script %}

todo/templates/todo/todo_index.html
{% extends 'base.html' %}

{% block title %}Vue.js - Django todo app{% endblock %}

{% block extra-style %}
<style>
    body {
        text-align: center;
        background-color: #ddd;
    }

    .inputBox {
        margin: auto;
        width: 70%;
        background: white;
        height: 50px;
        border-radius: 50px;
        line-height: 50px;
    }

    .inputBox .name {
        border-style: none;
        border-bottom: 1px solid #ddd;
        width: 90px;
        padding-left: 20px;
        line-height: 20px;
    }

    .inputBox .item {
        border-style: none;
        border-bottom: 1px solid #ddd;
        width: 400px;
        margin-left: 50px;
        padding-left: 20px;
        line-height: 20px;
    }

    .todoList {
        list-style: none;
        padding: 10px 0;
        text-align: left;
    }

    .todoList li {
        display: flex;
        height: 50px;
        line-height: 50px;
        margin: 0.5rem 0;
        padding: 0 0.9rem;
        background: white;
        border-radius: 5px;
    }

    .removeBtn {
        margin-left: auto;
        font-size: 20px;
    }

    .removeBtn:hover {
        color: red;
    }
</style>
{% endblock %}

{% block content %}
<div id='app'>

    <h1>My Todo App !</h1>
    <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
    <br>

    <div class="inputBox">
        <input class="name" type="text" placeholder="name ..."
               v-model.trim="name"><!--Vue.js 에서는 input으로 받는 데이터를 바인딩하기 위해서 v-model 디렉티브를 사용한다.-->
        <input class="item" type="text" placeholder="type anything welcomed ..."
               v-model.trim="todo" v-on:keyup.enter="add_todo()"> <!-- v-model.trim 수식어를 넣어주면 양 쪽으로 생긴 공백을 제거해준다.-->
        <!--v-on:keyup.enter="add_todo()" 는 enter 키를 눌러도 onclick 이벤트가 작동한다.-->
        <button class="btn btn-primary btn-sm"
                v-on:click="add_todo()">ADD
        </button>
        <!--ADD 버튼을 클릭했을 때 클릭 이벤트를 수신하기 위해서 v-on 디렉티브를 사용한다. 이벤트 핸들러는 add_todo()-->
    </div>
    <ul class="todoList">
        <li v-for="(todo, index) in todoList">
            <!--v-for 디렉티브를 사용하여 여러개의 todo 항목을 보여준다. vue.js에서는 index는 todo 뒤에 위치해야한다.-->
            <span>[[todo.name]]:: [[todo.todo]]</span>
            <!--for문을 돌면서 todo.name과 todo.todo를 가져와서 출력-->
            <span class="removeBtn"
                  v-on:click="remove_todo(todo, index)">x</span> <!-- index는 for loop에서 가져온다. -->
        </li>
    </ul>
</div>
{% endblock %}

{% block extra-script %}
<script src="https://unpkg.com/vue/dist/vue.min.js"></script>
<script src="https://unpkg.com/axios/dist/axios.min.js"></script>
<script>
    axios.defaults.xsrfCookieName = 'csrftoken';
    axios.defaults.xsrfHeaderName = 'X-CSRFToken';
    var vm = new Vue({
        delimiters: ['[[', ']]'], // 이런식으로 변경할 수가 있다
        el: '#app',
        data: {
            name: '',
            todo: '',
            todoList:[]
        },
        created: function() {
            console.log("created()...");
            this.fetch_all_todo(); // 메소드 호출
        },
        methods: {
            fetch_all_todo: function () {
                console.log("fetch_all_todo()...");

                var vm = this;
                axios.get('/api/todo/list/')
                    .then(function (res) { // 서버로 받은 데이터 res
                        console.log("GET RES", res);
                        vm.todoList = res.data; // this는 위치에 따라서 그 의미가 달라진다.
                    }) // 성공 시 callback 함수
                    .catch(function (err) {
                        console.log("GET ERR", err)
                    }) // 실패 시 callback 함수
            },
            add_todo: function () {
                console.log("add_todo()...");
                if (this.todo == '') return; // 만일 todo 항목을 입력을 안하면 아무일도 하지 않도록 return 시킨다.
                if (this.name == '') this.name = '홍길동'; // 사용자가 이름을 입력하지 않으면 this.name 에 홍길동을 넣는다.

                var vm = this;
                var postData = {name: this.name, todo: this.todo}; // post로 보내는 데이터의 key 명칭이 테이블 컬럼과 같아야한다.
                axios.post('/api/todo/create/', postData)
                    .then(function (res){
                        console.log("POST RES", res);
                        vm.todoList.push({id: res.data.id, name: res.data.name, todo: res.data.todo});
                // 사용자가 입력한 name과 todo를 v-model기능에 의해서 name과 todo 변수에 바인딩이 되고 name과 todo 변수값을
                // todoList 배열의 맨 뒤에 넣고 있는 것이다.
                    })
                    .catch(function (err){
                        console.log("POST ERR", err);
                    })
                this.name = this.todo = ''; // 사용자가 입력한 내용을 지워주는 기능 name과 todo를 비워준다.
            },
            remove_todo: function (todo ,index) { // <span class="removeBtn" v-on:click="remove_todo(todo, index)">x</span> <!-- index는 for loop에서 가져온다. -->
                console.log("remove_todo()...", index);
                if (confirm("Really delete ?") == false) return; // confirm 기능

                var vm = this;
                axios.delete('/api/todo/' + todo.id + '/delete/') // 99는 pk키
                    .then(function (res){ // 삭제 성공
                        console.log("DELETE RED", res);
                        vm.todoList.splice(index, 1);
                    })
                    .catch(function (err){ // 삭제 실패
                        console.log("DELETE ERR", err);
                    })
            },
        },
    })
</script>
{% endblock %}